### ISSUE TITLE
Service inventory started but did not initialize within the timeout period

### ISSUE THREAD

**Issue by rajdhandus** [ibm-apiconnect/cli#4]
$ node -v
v8.9.4
$ npm -v
5.6.0

Error: Service inventory started but did not initialize within the timeout period. Dumping log buffer.
[module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/apiconnect/node_modules/appmetrics/appmetrics.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/apiconnect/node_modules/appmetrics/index.js:23:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
module.js:672](url)

**Comment by smartmouse** [comment]
what is your OS?
what version of APIConnect did you install?

Please try the latest one,   apiconnect@4.0.24 Let us know if problem still exist?
You should use node 8.1.5.x with apiconnect.

**Comment by zinebibmtrainee** [comment]
I'm facing the same issue my os is windows 10 and the version of api connect is API Connect: v5.0.8.6-iFix (apiconnect: v4.0.24)
